db:
  username: postgres
  password: 20062006
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 1
    last: 2
    key: value
  pool:
    size: 10
    timeout: 20
  pools:
    - size: 10
      timeout: 20
    - size: 20
      timeout: 40

logging:
  level:
    root: warn
    by.max.spring.database.repository.pool: info
  file:
    name: by.max.logs
    path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/springdata
    username: postgres
    password: 20062006
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
